### ISSUE TITLE
Request for joining the Time Delay Challenge

### ISSUE THREAD

**Issue by zonggel** [DarkEnergyScienceCollaboration/TDCcosmoforecasts#1]
Hello,

I'm Zongge Liu, a 3rd year PhD student at Carnegie Mellon, and I work with Prof. Chad Schafer in statistics department. 

We've seen the previous time delay challenges and we hope we can contribute to this challenge later. 

I'm just curious if it's possible to unlock the data for the previous challenges, such as the TDC1 and the real time delay results for each rung.

Thanks!
Zongge

**Comment by drphilmarshall** [comment]
Hi Zongge, 

Apologies for slow reply, I was not expecting to see requests like this here! I updated the TDC website at http://timedelaychallenge.org/ with more information about future time delay challenges, please follow the instructions there for getting on the Good Teams email list. You should be able to find some useful starter data there too.

Cheers

Phil
